export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_SECTIONS = 'GET_SECTIONS';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const SET_USER_IS_NEW = 'SET_USER_IS_NEW';
export const GET_APP_DATA_SUCCESS = 'GET_APP_DATA_SUCCESS';
