export const COUNTRIES = [
  {
    ru: 'Киргизия',
    flag: '🇰🇬',
    code: 'KG',
    dialCode: '+996',
    mask: '999 99-99-99',
  },
  {
    ru: 'Россия',
    flag: '🇷🇺',
    code: 'RU',
    dialCode: '+7',
    mask: '999 999-99-99',
  },
  {
    ru: 'Казахстан',
    flag: '🇰🇿',
    code: 'KZ',
    dialCode: '+7',
    mask: '999 999-99-99',
  },
  { ru:"Афганистан",lt:"Afganistanas",tr:"Afganistan", en: 'Afghanistan', flag: '🇦🇫', code: 'AF', dialCode: '+93', mask: '999 999 9999' },
  { ru:"Аландские острова",lt:"Alandų salos",tr:"Aland adaları", en: 'Åland Islands', flag: '🇦🇽', code: 'AX', dialCode: '+358', mask: '999 9999999' },
  { ru:"Албания",lt:"Albanija",tr:"Arnavutluk", en: 'Albania',flag: '🇦🇱',code: 'AL', dialCode: '+355', mask: '999 999 9999' },
  { ru:"Алжир",lt:"Alžyras",tr:"Cezayir", en: 'Algeria',flag: '🇩🇿',code: 'DZ', dialCode: '+213', mask: '9999 99 99 99' },
  { ru:"американское Самоа",lt:"Amerikos Samoa",tr:"Amerikan Samoası", en: 'American Samoa',flag: '🇦🇸',code: 'AS', dialCode: '+1684', mask: '(999) 999-9999' },
  { ru:"андорра",lt:"Andora",tr:"Andorra", en: 'Andorra',flag: '🇦🇩',code: 'AD', dialCode: '+376', mask: '999 999' },
  { ru:"Ангола",lt:"Angoloje",tr:"Angora", en: 'Angola',flag: '🇦🇴',code: 'AO', dialCode: '+244', mask: '999 999 999' },
  { ru:"Ангилья",lt:"Angilija",tr:"Anguilla", en: 'Anguilla',flag: '🇦🇮',code: 'AI', dialCode: '+1264', mask: '(999) 999-9999' },
  { ru:"Антигуа и Барбуда",lt:"Antigva ir Barbuda",tr:"Antigua ve Barbuda", en: 'Antigua and Barbuda',flag: '🇦🇬',code: 'AG', dialCode: '+1268', mask: '(999) 999-9999' },
  { ru:"Аргентина",lt:"Argentina",tr:"Arjantin", en: 'Argentina',flag: '🇦🇷',code: 'AR', dialCode: '+54', mask: '999 99-9999-9999' },
  { ru:"Армения",lt:"Armėnija",tr:"Ermenistan", en: 'Armenia',flag: '🇦🇲',code: 'AM', dialCode: '+374', mask: '999 999999' },
  { ru:"Аруба",lt:"Aruba",tr:"Aruba", en: 'Aruba',flag: '🇦🇼',code: 'AW', dialCode: '+297', mask: '999 9999' },
  { ru:"Австралия",lt:"Australija",tr:"Avustralya", en: 'Australia',flag: '🇦🇺',code: 'AU', dialCode: '+61', mask: '9999 999 999' },
  { ru:"Австрия",lt:"Austrijoje",tr:"Avusturya", en: 'Austria',flag: '🇦🇹',code: 'AT', dialCode: '+43', mask: '9999 999999' },
  { ru:"Азербайджан",lt:"Azerbaidžanas",tr:"Azerbeycan", en: 'Azerbaijan',flag: '🇦🇿',code: 'AZ', dialCode: '+994', mask: '999 999 99 99' },
  { ru:"Багамские о-ва",lt:"Bahamos",tr:"Bahamalar", en: 'Bahamas',flag: '🇧🇸',code: 'BS', dialCode: '+1242', mask: '(999) 999-999' },
  { ru:"Бахрейн",lt:"Bahreinas",tr:"Bahreyn", en: 'Bahrain',flag: '🇧🇭',code: 'BH', dialCode: '+973', mask: '9999 9999' },
  { ru:"Бангладеш",lt:"Bangladešas",tr:"Bangladeş", en: 'Bangladesh',flag: '🇧🇩',code: 'BD', dialCode: '+880', mask: '99999-999999' },
  { ru:"Барбадос",lt:"Barbadosas",tr:"Barbados", en: 'Barbados',flag: '🇧🇧',code: 'BB', dialCode: '+1246', mask: '(999) 999-9999' },
  { ru:"Беларусь",lt:"Baltarusija",tr:"Belarus", en: 'Belarus',flag: '🇧🇾',code: 'BY', dialCode: '+375', mask: '9 999 999-99-99' },
  { ru:"Бельгия",lt:"Belgija",tr:"Belçika", en: 'Belgium',flag: '🇧🇪',code: 'BE', dialCode: '+32', mask: '9999 99 99 99' },
  { ru:"Белиз",lt:"Belizas",tr:"Belize", en: 'Belize',flag: '🇧🇿',code: 'BZ', dialCode: '+501', mask: '999-9999' },
  { ru:"Бенин",lt:"Beninas",tr:"Benin", en: 'Benin',flag: '🇧🇯',code: 'BJ', dialCode: '+229', mask: '99 99 99 99' },
  { ru:"Бермудские острова",lt:"Bermudai",tr:"Bermuda", en: 'Bermuda',flag: '🇧🇲',code: 'BM', dialCode: '+1441', mask: '(999) 999-9999' },
];
