export const ruTranslation = {
  translation: {
    tabs: {
      search: 'Поиск',
      favorites: 'Избранное',
      add: 'Разместить',
      chat: 'Отклики',
      profile: 'Профиль',
    },
    notifications: {
      noConnection: 'Нет соединения с интернетом',
    },
    login: 'Вход',
    enter: 'Войти',
    enterPhone: 'Введите номер телефона',
    getCode: 'Получить код по смс',
    scrollToTop: 'В начало списка',
    selectCountry: 'Выберите страну',
    phoneNumberVerification: 'Подтверждение номера \nтелефона',
    enterSmsCode: 'Введите код полученный по СМС',
    confirm: 'Подтвердить',
    waitingToSendSms: 'Можно запросить новый код через {{count}} сек',
    resendSms: 'Запросить новый код',
    logOut: 'Выход',
    orders: 'Мои заказы',
    completedOrders: '{{count}} выполненых заказов',
    settings: 'Настройки',
    notificationsText: 'Уведомления',
    personalData: 'Персональные данные',
    firstname: 'Имя',
    lastname: 'Фамилия',
    city: 'Город',
    phoneNumber: 'Номер телефона (не редактируется)',
    dateOfBirth: 'Дата Рождения',
    email: 'Эл. почта',
    save: 'Сохранить',
    welcome: 'Добро пожаловать',
    push_new_arrival: 'Новые поступления',
    push_sale: 'Специальные предложения',
    sms: 'SMS уведомления',
    addToCard: 'Добавить в корзину',
    new: 'Новинка',
    sale: 'Супер цена',
    soon: 'Скоро мы добавим сюда товары!',
    favoritesIsEmpty: 'Список избранных товаров пуст!',
    ordersIsEmpty: 'Список заказов пуст!',
    cardIsEmpty: 'Ваша корзина пуста!',
    goToMenu: 'Перейти в каталог',
    getOrder: 'Перейти к оформлению',
    newOrder: 'Новый заказ',
    emptyDataError: 'Заполните свои данные в профиле!',
    sendOrder: 'Отправить заявку',
    orderComplete: 'Наш менеджер свяжется с вами для уточнения деталей заказа',
    orderCompleteTitle: 'Заказ принят!',
    orderNum: 'Заказ №{{num}}',
    quantity: 'Количество: ',
    orderProcess: {
      N: 'Новый',
      S: 'Отправлен',
      Y: 'Выполнен',
      C: 'Отменен',
    },
    phoneIsInvalid: 'Не валидный номер телефона',
    codeIsInvalid: 'Введите код',
    newOrderFilter: 'В процессе',
    sendedOrderFilter: 'Завершенные',
  },
};
