export const ruTranslation = {
  translation: {
    tabs: {
      catalog: 'Каталог',
      favorites: 'Избранное',
      basket: 'Корзина',
      profile: 'Профиль',
    },
    notifications: {
      noConnection: 'Нет соединения с интернетом',
    },
    login: 'Вход',
    enterPhone: 'Введите номер телефона',
    getCode: 'Получить код по смс',
    scrollToTop: 'В начало списка',
    selectCountry: 'Выберите страну',
    phoneNumberVerification: 'Подтверждение номера \nтелефона',
    enterSmsCode: 'Введите код полученный по СМС',
    confirm: 'Подтвердить',
    waitingToSendSms: 'Можно запросить новый код через {{count}} сек',
    resendSms: 'Запросить новый код',
    logOut: 'Выход',
    orders: 'Мои заказы',
    completedOrders: '{{count}} выполненых заказов',
    settings: 'Настройки',
    notificationsText: 'Уведомления',
    personalData: 'Персональные данные',
    firstname: 'Имя',
    lastname: 'Фамилия',
    city: 'Город',
    phoneNumber: 'Номер телефона (не редактируется)',
    save: 'Сохранить',
    welcome: 'Добро пожаловать',
    push_new_arrival: 'Новые поступления',
    push_sale: 'Специальные предложения',
    sms: 'SMS уведомления',
    addToCard: 'Добавить в корзину',
    new: 'Новинка',
    sale: 'Супер цена',
    soon: 'Скоро мы добавим сюда товары!',
    favoritesIsEmpty: 'Список избранных товаров пуст!',
    cardIsEmpty: 'Ваша корзина пуста!',
    goToMenu: 'Перейти в каталог',
    getOrder: 'Перейти к оформлению',
    newOrder: 'Новый заказ',
  },
};
